import { PrismaClient, GroupLevel } from '@prisma/client'

const prisma = new PrismaClient()

const groups: { name: string; level: GroupLevel; children: string[] }[] = [
  {
    name: "Qushcha",
    level: "ORTA",
    children: [
      "Alimov Shaxzod",
      "Akmalova Fariza",
      "Baratov Mustafo",
      "Botirjonov Usmon",
      "Feruzova Shaxribonu",
      "Farxodova Laylo",
      "Faxriddinova Iymona",
      "Latipov Kamron",
      "Murodov Muxiddin",
      "Murodullaeva Soliha",
      "Oybekova Xanifabonu",
      "Obidova Fotima",
      "Raxmatova Iymona",
      "Sodiqov Amirxon",
      "Nasimov Nurmuxammad",
      "Xoliqova Sabina",
      "Yoqubov Xusan",
      "Yoqubov Amirxon",
      "Gʻayratova Ezoza",
      "Ganiyev Sardor",
      "Gʻaniyev Muxammad",
      "Shonazarova Muslima",
      "Shomamatov Mustafo",
      "Shermurodov Muxammad",
      "Turopov Yaxyobek",
      "Tursunmurodov Javlon",
      "Yarashov Ibrohim",
      "Umriddinov Alibek",
    ],
  },
  {
    name: "Ayiqcha",
    level: "ORTA",
    children: [
      "Farhodov Muhammadali",
      "Muzaffarov Saidumar",
      "Fayziyev Umidjon",
      "Salohiddinova Xadicha",
      "Akbarov Amirxon",
      "Abduqahhorova Gulasal",
      "Xolboyeva Malikaxon",
      "Mardonova Solihabonu",
      "Kamolova Gavharoy",
      "Toyirova Anora",
      "Shavkatov Akobir",
      "Maratova Sadia",
      "Gayratov Muhammad",
      "Rahimov Nurmuhammad",
      "Ismatulloyeva Parizoda",
      "Ibodullayev Amiriddin",
      "Alisherova Soliha",
      "Sayfiddinova Mehrimoh",
      "Abdullayev Muhammadali",
      "Abduhakimova Farzona",
      "Hamidjonov Muhammadali",
      "Sobirov Aminjon",
      "Otaxonov Yusuf",
      "Muhiddinova Ifora",
      "Qudratova Dilsoʻz",
      "Rustamova Soliha",
      "Shadiyev Muslimbek",
      "Tilavov Abdulloh",
      "Maxmasoliyeva Muslima",
      "Axmedov Akbarshox",
      "Oltinova Jasmina",
      "Qobilova Lobar",
      "Shavkatov Abumuslim",
      "Oripov Shohjahon",
    ],
  },
  {
    name: "Xoʻrozcha",
    level: "ORTA",
    children: [
      "Aydarbaeva Neslebeli",
      "Akmaljonova Imona",
      "Abdurasulovа Asilabonu",
      "Ahmadov Muhammad",
      "Baxtiyorova Margiyena",
      "Farmonov Usmon",
      "Farxodov Muxriddin",
      "Fazliddinov Abdulloh",
      "Farxodova Roziyabegim",
      "Faxriddinova Afruza",
      "Gʻolibov Javohir",
      "Gafforov Jasur",
      "Xasanov Muhammad",
      "Komilova Mukaddam",
      "Kulliyeva Melek",
      "Nasriddinov Muhammadaziz",
      "Nurislomov Muhammadali",
      "Navruzov Jasurbek",
      "Sayfiddinov Dilbek",
      "Salimov Asadbek",
      "Sirojiddinova Tumaris",
      "Saparbaev Allabergen",
      "Shokirov Muhammad",
      "Togabekova Shahzoda",
      "Toshtimirova Shirin",
      "Ziyadullayeva Shahlo",
      "Zoyirova Zahro",
      "Erkinov Ulugʻbek",
      "Egamqulov Nurmuhammad",
      "Ergashova Nozanin",
      "Xurramova Soliha",
    ],
  },
  {
    name: "Yulduzcha",
    level: "KATTA",
    children: [
      "Hamdamov Amir",
      "Salomova Sevinch",
      "Toʻrayev Ibrohim",
      "Iskandarova Muslima",
      "Saparaliyev Doston",
      "Rahmonqulov Ali",
      "Bozorboyev Abdulloh",
      "Nurmatov Alisher",
      "Gʻulomov Akbarxon",
      "Abdurahmonov Muhammadsolih",
      "Erkinova Soliha",
      "Rustamov Sinan",
      "Ochildiyev Ibrohim",
      "Aliyev Azamjon",
      "Shomuradov Eldorbek",
      "Sharipov Habibullo",
      "Shavkatova Zaynabegim",
      "Ebodullayeva Gulnafis",
      "Hamroyev Muhammadali",
      "Vafoyev Ixlosbek",
      "Teshaqulova Dilsora",
      "Erkinov Muhammadumar",
      "Xolboyev Dinmuhammad",
      "Rahmatullayeva Soliha",
      "Abdusalimov Ayubxon",
      "Bahromova Sevara",
      "Umarova Imona",
    ],
  },
  {
    name: "Momoqaymoq",
    level: "KATTA",
    children: [
      "Aktamova Zilola",
      "Akromova Muslima",
      "Akbarova Mehrimoh",
      "Mamatova Dilbar",
      "Baxtiyorov Muhammadali",
      "Baxtiyorov Muzaffar",
      "Faxridinov Amirxon",
      "Muhammadova Laylo",
      "Muhiddinov Shaxfam",
      "Nurjonov Jafar",
      "Olimov Jahongir",
      "Roʻziqulov Damir",
      "Fayzullayev Fayzbek",
      "Togʻayev Muhammadali",
      "Suvonqulov Umar",
      "Toʻlqinova Mushtariy",
      "Suvonova Marjona",
      "Shokirov Ulugʻbek",
      "Oʻtkirov Diyor",
      "Oʻtkirova Soliha",
      "Zaynidinov Ibrohim",
      "Sohibjonov Samir",
      "Abduraxmonova Soliha",
      "Shavkatova Dunyo",
      "Islomova Soliha",
    ],
  },
  {
    name: "Chumchuqcha",
    level: "KATTA",
    children: [
      "Abduhalilova Mubina",
      "Anvarova Fotima",
      "Anvarova Zuhra",
      "Akbarova Fotima",
      "Ahmadova Mastura",
      "Asadullayeva Nurbonu",
      "Akbaraliyeva Soliha",
      "Begaliyev Alixan",
      "Begmatov Muhammadali",
      "Erkinov Muhammad",
      "Erkinov Shahram",
      "Ergashev Kamron",
      "Ergashev Mehroj",
      "Murodullayev Amarbek",
      "Murodullayev Asilbek",
      "Bahronov Muhammad",
      "Muhammadiyorova Dilnura",
      "Olimov Imron",
      "Odilova Xadicha",
      "Gʻolibova Marjona",
      "Gʻulomjonova Mehrimoh",
      "Rahimova Imona",
      "Rajabova Muslima",
      "Umarov Umarali",
      "Umidov Umar",
      "Hakimova Amina",
      "Oʻtkirova Sevara",
      "Zokirova Malika",
      "Qahramonova Kamila",
      "Xidirov Asadbek",
      "Oʻktamov Muhammadali",
      "Zoirov Habibulloh",
    ],
  },
  {
    name: "Quyoncha",
    level: "TAYYORLOV",
    children: [
      "Abdullayeva Lola",
      "Bahodirov Jahongir",
      "Ermamatov Imron",
      "Kamolov Samandar",
      "Ergasheva Muslima",
      "Qilichov Alijon",
      "Mamanazarov Elnur",
      "Jahongirov Miron",
      "Sunnatullayeva Jasmina",
      "Sunnatullayeva Samira",
      "Ilhomjonov Akobir",
      "Oʻtkirov Abdurahmon",
      "Xudoyqulov Otabek",
      "Qudratov Davlat",
      "Nomozboyeva Farangiz",
      "Roʻziqulova Ifora",
      "Roʻziyeva Ifora",
      "Isoqulov Muhammad",
      "Tuyboyev Akbar",
      "Ravshanov Fazliddin",
      "Rashidova Fariya",
      "Salomov Imron",
      "Sayfiddinov Shaxram",
      "Farhodova Aziza",
      "Zubaydullayeva Billura",
      "Samadov Abduhamid",
      "Umidova Imona",
    ],
  },
  {
    name: "Boʻgʻirsoq",
    level: "TAYYORLOV",
    children: [
      "Abdusalomov Alisher",
      "Yusupov Javohir",
      "Yusupova Shukrona",
      "Shavkatov Xondamir",
      "Nurnazarov Shohrux",
      "Nurmatov Quvonchbek",
      "Zoyadullayeva Malika",
      "Karomoddinova Afroʻza",
      "Ashurova Afroʻza",
      "Toʻxtapoʻlatov Shohjahon",
      "Sharipov Muhammadamin",
      "Rahimova Marjona",
      "Rahmonov Muhammadali",
      "Ismatullayev Ulugʻbek",
      "Muzaffarov Mustafo",
      "Bahromov Mustafo",
      "Isomiddinov Islom",
      "Sultonov Muhammad",
      "Akramov Temur",
      "Najmiddinov Usmon",
      "Bekmurodov Ibrohim",
      "Abdullayev Saidamir",
      "Abdullayeva Asal",
      "Yunusbekov Aminjon",
      "Gapporova Iymona",
    ],
  },
  {
    name: "Qoʻngʻiroqcha",
    level: "KICHIK",
    children: [
      "Akramjonov Abduloh",
      "Rustamov Yusuf",
      "Rustamova Marjona",
      "Shuxratov Muhadbilol",
      "Samadov Abubakirr",
      "Isroilov Amirbek",
      "Botirov Abdurashid",
      "Botirov Abduhamid",
      "Akbarova Durdona",
      "Gayratova Okila",
      "Vaxobov Baxtbek",
      "Kamolova Habiba",
      "Sobitova Mereke",
      "Zokirova Shukrona",
      "Xolmirodova Iymona",
      "Ergasheva Xadicha",
      "Gaybullayev Muhammadali",
      "Alimov Dovud",
      "Xasanov Muhammadamin",
      "Ahmadova Xadicha",
      "Ibodullayeva Ifora",
      "Boxodirova Ifora",
      "Oʻtkirova Marjona",
      "Aliyeva Sabrina",
      "Qosimova Muslima",
      "Xamroev Biloloddin",
    ],
  },
  {
    name: "Bulbulcha",
    level: "KICHIK",
    children: [
      "Xayriddinova Xonzoda",
      "Shomamatova Farzona",
      "Muxiddinova Afsona",
      "Pardaboyeva Mubina",
      "Muxiddinova Yasmina",
      "Mamalatipova Oyshabonu",
      "Suyunova Muslima",
      "Najmiddinov Mirziyo",
      "Akramova Munisa",
      "Ahmadjonov Usmon",
      "Allayarov Abdulloh",
      "Alikulov Umarbek",
      "Imominov Muhammadrizo",
      "Sobitov Muhammad",
      "Islomova Shahzoda",
      "Turgunov Imron",
      "Sagdullayev Mustafo",
      "Abdusamadov Xumoyon",
      "Maxmadaliyeva Fotima",
      "Nurmamatov Davron",
      "Qobilov Boburjon",
      "Shodiyeva Parvina",
      "Jamoliddinova Dilnura",
      "Normurodov Muhammadyusuf",
      "Maxmadaliyeva Zuhra",
      "Begalova Amina",
      "Shamsiddinova Soliha",
    ],
  },
]

async function main() {
  for (const g of groups) {
    const group = await prisma.group.upsert({
      where: { name_level: { name: g.name, level: g.level } },
      create: { name: g.name, level: g.level },
      update: {},
    })
    for (const fullName of g.children) {
      await prisma.child.upsert({
        where: { fullName_groupId: { fullName, groupId: group.id } },
        create: { fullName, groupId: group.id },
        update: {},
      })
    }
    console.log(`✔ ${g.level} – ${g.name}: ${g.children.length} children`)
  }
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
